version: 2
updates:
  # NPM dependencies for React app
  - package-ecosystem: "npm"
    directory: "/notes"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: build
    labels:
      - "dependencies"
      - "automerge"
    versioning-strategy: increase
    reviewers:
      - "dangphung4"
    groups:
      dependencies:
        patterns:
          - "*"

  # NuGet dependencies for Aspire projects
  - package-ecosystem: "nuget"
    directory: "/NotesAspire"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: build
    labels:
      - "dependencies"
      - "automerge"
    reviewers:
      - "dangphung4"
    groups:
      aspire-dependencies:
        patterns:
          - "Aspire.*"
      microsoft-dependencies:
        patterns:
          - "Microsoft.*"

  # GitHub Actions workflows
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: ci
    labels:
      - "dependencies"
      - "automerge" 