name: Conventional Commits

on:
  pull_request:
    types: [opened, synchronize, reopened, edited]
    branches: [ main, master, development ]
  push:
    branches: [ main, master, development ]

permissions:
  contents: read
  pull-requests: read

jobs:
  commit-lint:
    name: Validate Conventional Commits
    runs-on: ubuntu-latest
    
    # what this does: prevents the action from running twice on PRs from the same repo
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository
    
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          
      - uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: 'npm'
          
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: npm-${{ hashFiles('package-lock.json') }}
          restore-keys: npm-
          
      - name: Install commitlint
        run: |
          npm install --save-dev @commitlint/config-conventional @commitlint/cli
          
      - name: Create commitlint config
        run: |
          echo '{
            "extends": ["@commitlint/config-conventional"],
            "rules": {
              "type-enum": [
                2,
                "always",
                [
                  "feat",
                  "fix",
                  "docs",
                  "style",
                  "refactor",
                  "perf",
                  "test",
                  "build",
                  "ci",
                  "chore",
                  "revert"
                ]
              ],
              "type-case": [2, "always", "lower"],
              "type-empty": [2, "never"],
              "subject-empty": [2, "never"],
              "subject-full-stop": [2, "never", "."],
              "header-max-length": [2, "always", 72]
            }
          }' > .commitlintrc.json
          
      - name: Validate commits
        run: |
          if [ "${{ github.event_name }}" = "pull_request" ]; then
            npx commitlint --from ${{ github.event.pull_request.base.sha }} --to ${{ github.event.pull_request.head.sha }} --verbose
          else
            npx commitlint --from ${{ github.event.before }} --to ${{ github.event.after }} --verbose
          fi
        
      - name: Check PR title
        if: github.event_name == 'pull_request'
        run: |
          echo "${{ github.event.pull_request.title }}" | npx commitlint --verbose
