name: Conventional Commits

on:
  pull_request:
    types: [opened, synchronize, reopened, edited]
    branches: [ main, master, development ]
  pull_request_target:
    branches: [ main, master, development ]
  push:
    branches: [ main, master, development ]

permissions:
  contents: read
  pull-requests: read

jobs:
  commit-lint:
    name: Validate Conventional Commits
    runs-on: ubuntu-latest
    
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository
    
    defaults:
      run:
        working-directory: notes
    
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: 'npm'
          cache-dependency-path: notes/package-lock.json
          
      - name: Install commitlint
        run: |
          npm install --save-dev @commitlint/config-conventional @commitlint/cli
          
      - name: Validate commits
        run: |
          if [ "${{ github.event_name }}" = "pull_request" ]; then
            npx commitlint --from ${{ github.event.pull_request.base.sha }} --to ${{ github.event.pull_request.head.sha }} --verbose
          else
            npx commitlint --from ${{ github.event.before }} --to ${{ github.event.after }} --verbose
          fi
        
      - name: Check PR title
        if: github.event_name == 'pull_request'
        run: |
          echo "${{ github.event.pull_request.title }}" | npx commitlint --verbose
