name: Conventional Commits

on:
  pull_request:
    types: [opened, synchronize, reopened, edited]
    branches: [ main, master, development ]
  pull_request_target:
    branches: [ main, master, development ]
  push:
    branches: [ main, master, development ]

permissions:
  contents: read
  pull-requests: read

jobs:
  commit-lint:
    name: Validate Conventional Commits
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 10 # Only fetch last 10 commits
          ref: ${{ github.event.pull_request.head.sha }}
          
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: 'npm'
          cache-dependency-path: notes/package-lock.json
          
      - name: Install commitlint
        working-directory: notes
        run: |
          npm install --save-dev @commitlint/config-conventional @commitlint/cli
          
      - name: Copy commitlint config
        run: |
          cp .commitlintrc.json notes/
          
      - name: Validate commits
        working-directory: notes
        run: |
          if [ "${{ github.event_name }}" = "pull_request" ] || [ "${{ github.event_name }}" = "pull_request_target" ]; then
            # For PRs, check only commits in the PR
            BASE_SHA="${{ github.event.pull_request.base.sha }}"
            HEAD_SHA="${{ github.event.pull_request.head.sha }}"
            
            if [ -z "$BASE_SHA" ] || [ -z "$HEAD_SHA" ]; then
              echo "Warning: Could not determine base or head SHA. This is expected for pull_request_target events."
              exit 0
            fi
            
            echo "Checking commits between $BASE_SHA and $HEAD_SHA"
            git fetch origin $BASE_SHA
            BASE_SHA=$(git merge-base $BASE_SHA $HEAD_SHA)
            
            # Skip bot commits during validation
            git log $BASE_SHA..$HEAD_SHA --format="%H %ae %s" | \
            while read -r hash email subject; do
              if [[ ! $email =~ .*\[bot\]@.*|.*bot@.* ]]; then
                echo "$subject" | npx commitlint --verbose
              fi
            done
          else
            # For pushes, check only the latest commit if not from a bot
            AUTHOR_EMAIL=$(git log -1 --format="%ae")
            if [[ ! $AUTHOR_EMAIL =~ .*\[bot\]@.*|.*bot@.* ]]; then
              npx commitlint --from HEAD~1 --to HEAD --verbose
            fi
          fi
        
      - name: Check PR title
        if: github.event_name == 'pull_request' || github.event_name == 'pull_request_target'
        working-directory: notes
        run: |
          # Skip PR title check if PR is from a bot
          if [[ ! "${{ github.event.pull_request.user.login }}" =~ .*\[bot\]$ ]]; then
            echo "${{ github.event.pull_request.title }}" | npx commitlint --verbose
          fi